### ISSUE TITLE
m_mp12oanum Variable

### ISSUE THREAD

**Issue by jrgant** [EpiModel/ARTnet#17]
This question applies to the wide version of the ARTNet dataset.

I see that the variable `m_mp12oanum2` is renamed `cuml.pnum`. However the dataset also contains a variable named `m_mp12oanum` that doesn't appear to be documented in the Data Dictionary. 

In checking `cuml.pnum` and `m_mp12oanum` against one another, they appear to contain different information, so I was wondering how to interpret the latter.

**Comment by smjenness** [comment]
@pragativprasad Could you please look into this?

**Comment by pragativprasad** [comment]
@jrgant `m_mp12oanum` should be described in line 104 of the data dictionary: it's an AMIS Survey variable, while `m_mp12oanum2`/`cuml.pnum` are ARTNet Survey variables.

**Comment by smjenness** [comment]
Thanks. @jrgant please let us know if you need further assistance with this.

**Comment by jrgant** [comment]
Thanks for clarifying. Just wanted to make sure I was using the right variable. I'll close this issue.
