### ISSUE TITLE
Netparams Cut Function Issue - Model Age Terms

### ISSUE THREAD

**Issue by connor-vanmeter** [EpiModel/ARTnet#20]
## Description
The lower age limit is excluded in determination of age-related nodefactor and nodematch network parameters.

## Steps to Reproduce

1. Add browser() to ARTnet package Netparams.R to browse through the build_netparams function. Save Netparams.R. Build and Install the updated ARTnet package and restart R. Load ARTnet.

2. Run the below ARTnet Script
```library("ARTnet")
library("tidyverse")

#1. Epistats: Specify geographic features, as well as race stratification and total age range
#under consideration
epistats <- build_epistats(geog.lvl = "city", geog.cat = "Chicago", race = TRUE, age.limits = c(16, 29),
                           age.breaks = c(18, 24))

#2. Netparams: Specify age categories if needed, or let ARTnet determine age categories by number of
#categories desired
netparams <- build_netparams(epistats = epistats, smooth.main.dur = TRUE)
```

3. Browsing through build_netparams, run the script to the below line:
`lmain$index.age.grp <- cut(lmain$age, age.breaks, labels = FALSE)`

4. Evaluate `lmain$age` alone

5. Evaluate `cut(lmain$age, age.breaks, labels = FALSE)` alone

6. When the user writes the build_epistats function, they may specify age.limits and age.breaks. In the above example, the implications for specifying `age.limits = c(16,29)` is to filter the ARTnet.long dataset to include only egos with age between the user specified lower and upper age limits, **inclusively**. 

The user then may specify age.breaks. In the above example, the expected outcome of specifying `age.breaks = c(18,24)` is to determine network target statistics and eventually model fit for age.breaks + 1 age groups, with the following ages:
Age Group 1: 16-18 year olds
Age Group 2: 19-24 year olds
Age Group 3: 25-29 year olds

`Age.breaks = c(18,24)` is passed into epistats and transformed with this line of code:
`age.breaks <- unique(sort(c(age.limits[1], age.breaks, age.limits[2])))`

The resulting output of age.breaks after the transformation is the following vector:
(16, 18, 24, 29)

The new, transformed age breaks is then read into build_netparams:
`age.breaks <- epistats$age.breaks`

A new variable defining the number of age groups, age.grps is appropriately defined as:
`age.grps <- length(age.breaks) - 1`

The ARTnet.long dataframe is filtered to only include egos with ages within the user-defined age limits: `l <- subset(l, age >= age.limits[1] & age <= age.limits[2])`

When defining index and partner age groups for the nodefactor and nodematch age terms, the R cut function is used passing in the ARTnet.long$age column, with an allowable range of values inclusively between 16 and 29, the lower and upper age limits. The cut function then "breaks apart" the ARTnet.long$age column into a number of age groups equal to age.grps (number of age breaks - 1).

But the cut function in R is written in such a way that it is exclusive of the lower bound age break. See this example below which is a simplified demonstration of the issue:
```
age <- c(15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30)
age_cut <- cut(age,breaks = c(16,18,24,29), labels = FALSE)
age.df <- data.frame(age,age_cut)
age.df
```

![image](https://user-images.githubusercontent.com/31194265/72920585-9a455a80-3d17-11ea-886a-fcfe504a9d2d.png)

The result is that age group 1 corresponding to egos with age 16-18 does not include egos with age 16.

## Steps to Resolve

The simplest solution may be to subtract one from the lower bound when creating the transformed age.break vector in EpiStats.R:
`age.breaks <- unique(sort(c(age.limits[1] - 1, age.breaks, age.limits[2])))`

But may need to assess impact of the change if age.breaks is used elsewhere.

**Comment by AdrienLeGuillou** [comment]
The `cut` function has a parameter `include.lowest` that will make the first interval inclusive of the lower bound, 16 in this case.

**Comment by connor-vanmeter** [comment]
Hi @andsv2 . Met with Sam this afternoon and he suggested that this issue may be on your radar with some changes that are planned or in progress with ARTnet. Just wanted to make you aware of the issue if you haven't seen it already. Adrien suggested a possible fix by including the `include.lowest` parameter in the cut function. Please let me know if you have or will take up the changes or if you would like me to make the update. Thanks!

**Comment by andsv2** [comment]
@connor-vanmeter thanks for bringing this up. We've made changes to ARTnet that should avoid this issue. See `build_epistats` help file for how age cuts are defined.
