### ISSUE TITLE
build_netparams throws an error with default geog.lvl=NULL

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/ARTnet#22]
The docs for `build_epistats()` say:

```
geog.lvl: level of geographic stratification desired. Acceptable values are "city", "state", "region", 
and "division" corresponding to city, state, census region, census division and complete geographic
 area respectively. Default value is "NULL", indicating no geographic stratification.
```

But leaving it at the default NULL generates an error for `build_netparams` at this line:

https://github.com/EpiModel/ARTnet/blob/a834bd8ecd060aa4651b9ac7dca496ac78331b6d/R/NetParams.R#L53

```
> epistats$geog.d
character(0)
```

Further down in netparams, there is code suggesting NULL is acceptable for `geog.lvl`
```
## edges ----
  if (is.null(geog.lvl)) {
    mod <- glm(deg.main ~ 1,
               data = d, family = poisson())
    # summary(mod)
```

**Comment by Shmelder** [comment]
I have been looking through the code for a while now, and have found a few problem spots.  I have created a pull request with modifications for what should happen when geog.lvl  (and geog.cat) are missing.  

The first issue has to do with the epistats function and is what I think created the initial problems issue.  When l$geog and d$geog are NULL, the as.character function coerces the NULL value to be a character vector with zero length: 

https://github.com/EpiModel/ARTnet/blob/a834bd8ecd060aa4651b9ac7dca496ac78331b6d/R/EpiStats.R#L461-L462 

This then causes problems when the epistats object is called by the build_netparams function here:

https://github.com/EpiModel/ARTnet/blob/a834bd8ecd060aa4651b9ac7dca496ac78331b6d/R/NetParams.R#L53-L56

The next issue has to do with when the geog.lvl is NULL.  When this is the case, I am assuming geog.cat should also be null (If this is not the case, what I am writing is likely incorrect).  In this case, errors are produced for subsetting that happens in places like this (I think line 474 should be removed in cases where geog is NULL): 

https://github.com/EpiModel/ARTnet/blob/a834bd8ecd060aa4651b9ac7dca496ac78331b6d/R/NetParams.R#L470-L477

and errors are created in places like this (I think the subsetting on line 742 should not happen):

https://github.com/EpiModel/ARTnet/blob/a834bd8ecd060aa4651b9ac7dca496ac78331b6d/R/NetParams.R#L732-L756

I will send the pull request once I remember how to do one.

**Comment by martinamorris** [comment]
I've pulled ARTnet with @andsv2 branch `ARTnet_hivprev` that I believe includes the modifications in 
607f466 .  Building that locally I'm getting the following errors:

```
> epistats <- build_epistats(epistats)
Error in build_epistats(epistats) : 
  Selected geographic feature must be one of: city, state, region or division
In addition: Warning message:
In if (!(geog.lvl %in% geog_names)) { :
  the condition has length > 1 and only the first element will be used
```
And when specifying the region:
```
> epistats <- build_epistats(geog.lvl = "region", geog.cat = "4")
> netparams <- build_netparams(epistats)
> netstats <- build_netstats(epistats, netparams, network.size = 14410)
 Error: 'race.dist' is not an exported object from 'namespace:ARTnetData' 
```

**Comment by Shmelder** [comment]
I think the first error you get is because you should not pass epistats to build_epistats.

The other variable appears to occur here:
https://github.com/EpiModel/ARTnet/blob/607f4661ae835277a56fb4f25723cee3820c5420/R/NetStats.R#L46

and needs to be changed to (I think)

```{r}
race.dist <- ARTnetData::race.dist.national
```

**Comment by andsv2** [comment]
Afternoon folks; first thanks for bringing this to my attention. My fault for dropping the ball on debugging of these changes for mass use. 

In regards to the second issue, if you are going to use the dev. version of ARTnet with the geographic changes, ARTnetData@d5423b2 should be used as it changes the way ARTnetData handles the different regions. Depending on what version of EpiModelHIV you are using, that likely needs to be changed to. The branch of EpiModelHIV that I am currently using with the development branch of ARTnet is EpiModelHIV@6dbf7dc.

Again, apologies for the issues you are having and please don't hesitate to let me know if I can help further.

**Comment by martinamorris** [comment]
Yep, sorry I fixed the typo in the issue (and the code).   Will try the install stack above.

**Comment by andsv2** [comment]
It is actually good that this was brought up as it pulls out an error in dissolution_coefs. Lemonade out of lemons.

**Comment by martinamorris** [comment]
@andsv2 There's one issue here -- we're using EpiModelHIV-p@WHAMP.  Do you know how we might be able to merge the key changes there?

**Comment by andsv2** [comment]
@martinamorris morning Martina. I will review this today and see about getting it working on WHAMP.

**Comment by andsv2** [comment]
Hello again @martinamorris: is WHAMP@06c196a a good commit to work from?

**Comment by martinamorris** [comment]
Just to be sure -- which version of `EpiModel` should I be using this with now?

**Comment by andsv2** [comment]
I've been using the latest version of EpiModel on git (`EpiModel@1a609be` right now) for testing. It still has the default behavior for `dissolution_coefs`, however the change to ARTnet default expected mortality rate takes care of that.

**Comment by andsv2** [comment]
Updated with `EpiModel/ARTnet@95f6d12`.
