### ISSUE TITLE
build_netstats now throws errors

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/ARTnet#24]
Using:
@andsv2 @Shmelder 

```
 ARTnet         * 2.0.0    2020-02-12 [?] Github (epimodel/ARTnet@a834bd8)    
 ARTnetData     * 1.1      2020-02-01 [?] Github (EpiModel/ARTnetData@1d8ec6e)
 EpiModel       * 1.7.3    2020-02-01 [1] Github (statnet/EpiModel@2c131f0)
```
I am getting this error now:
```
> epistats <- build_epistats()
> netparams <- build_netparams(epistats)
> netstats <- build_netstats(epistats, netparams)
Warning message:
In log(pg.thetaX/(ps2.thetaX - pg.thetaX)) : NaNs produced
```

which is coming from here:
https://github.com/statnet/EpiModel/blob/bca2ab0a64fde51938e5a10aafecda3905cdf086/R/net.utils.R#L420

**Comment by andsv2** [comment]
@martinamorris; yes this is an error I saw yesterday. About a year ago we changed dissolution_coefs to check for mortality rate being too high; however looking through the code it seems that it was only changed for when formation = ~edges. That error occurs with a more complex formation formula as it's checking all terms in the model. I'll change that so that it gives an informative error as well in that case.

**Comment by martinamorris** [comment]
Thanks @andsv2 .  Just to be clear, are you saying it's a true error?  If so, then the default building sequence for ARTnet throws an error, which is a problem.

On our end, we're trying to get an example set up for benchmarking this weekend -- and we need the ARTnet build sequence to work for this.  Let me know if you think this won't be done by Friday, so I can reorganize our workplan, thx.

**Comment by andsv2** [comment]
Good morning @martinamorris. Yes it looks like the default mortality rate needs to be lowered when using only default values of ARTnet. It is changed now.

**Comment by martinamorris** [comment]
Good morning @andsv2 :)

With this stack:
```
> sessioninfo::package_info()
 package        * version  date       lib source                                          
 ARTnet         * 2.0.0    2020-02-13 [1] Github (epimodel/ARTnet@f32ff8f)    
 ARTnetData     * 1.0      2020-02-01 [1] Github (EpiModel/ARTnetData@1d8ec6e)
```
I'm getting this odd error now:
```
> epistats <- build_epistats()
Error: lazy-load database 'C:/Users/Martina Morris/Documents/R/win-library/3.6/ARTnet/R/ARTnet.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1 
```

**Comment by martinamorris** [comment]
Nevermind!  It works.  The problem was that I was trying to test the `dev` version with the `ARTnet` Rstudio project set to the default branch.

Now everything works perfectly!  Thanks so much for your help :).  I'll be working on the WHAMP stuff next so will test whether the changes you made there work.

**Comment by andsv2** [comment]
That's excellent news. In regards to WHAMP, it should not work, as there are changes in the acts and condom modules that do not look like they have been pulled in. It looks like some of the geographic changes made it in, but it will definitely break if building network objects using default values of ARTnet.

**Comment by martinamorris** [comment]
I think the WHAMP compatibility issue deserves it's own thread, on the `EpiModelHIV-p` repo.  So will follow up there.

Really appreciate your help here, thx :)

**Comment by andsv2** [comment]
Issue closed by lowering default expected mortality rate. Core change being addressed by https://github.com/statnet/EpiModel/pull/331.

**Comment by martinamorris** [comment]
> Issue closed by lowering default expected mortality rate. Core change being addressed by [statnet/EpiModel#331](https://github.com/statnet/EpiModel/pull/331).

Changes not yet merged with that pull request, is that right?

**Comment by smjenness** [comment]
@andsv2 Don't close issues associated with a PR until the PR is merged.
@martinamorris we are close to merging this, and will keep you updated

**Comment by smjenness** [comment]
statnet/EpiModel#331 is now merged, so closing this issue.
