### ISSUE TITLE
EpiModelHIV-p@WHAMP-2.0 now throws errors

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/ARTnet#25]
@andsv2 the new branch you merged for us is complaining about not finding the geogYN variable:

```
sim <- netsim(ee.netest.full, param, init, control)

Starting Network Simulation...Error in eval(predvars, data, env) : object 'geogYN' not found
```
This is coming from the `mod.acts` function. 

I don't see an explicit reference to 'geogYN' in that function, so I'm not sure what is triggering this error.  

But the original `WHAMP` branch still works.

Any changes in CombPrev come to your mind that may explain the error in the new merged branch?

**Comment by andsv2** [comment]
I'm take a look at this. If using no geography that shouldn't happen.

**Comment by martinamorris** [comment]
> I'm take a look at this. If using no geography that shouldn't happen.

Zoe make a couple of changes and I'll be pulling new versions and trying 
tomorrow.  Thx.

**Comment by andsv2** [comment]
Morning @martinamorris; I am trying to replicate the error using the the test script you mentioned last week, however I'm still getting those `data.table` errors on my end. However that error should only be showing up if geographic stratification has been used in ARTnet (geog.lvl = "Something other than NULL") and is then expected in the acts and condom modules from EpiModelHIV.

Do you have a full workflow script I can take a gander at and sessionInfo()?

**Comment by martinamorris** [comment]
Morning @andsv2 .  Here is what @syzoekao  sent last night by email:

> I won't be able to work on WHAMP tomorrow so I wanted to fix the errors tonight. I also encountered the error that you mentioned on Skype. It was because the new CombPrev-2.0 handles the parameters exported from ARTnet slightly differently. I recreated epistats and netstats objects based on the updated versions of ARTnet (2.0.0) and ARTnetData (1.1). I think the new data objects should fix the errors. 

> I already pushed the changes to WHAMP-2.0. In addition, I also pushed some changes to the DSdata package (due to ARTnet changes). Please let me know if it works for you after you pull the  changes. Thanks!

So here is what I have done.   I've updated the following packages from their repos:

ARTnet
ARTnetData
MakeDSdata (note @andsv2 , this is our version to make "downstream" data from ARTnet)
EpiModelHIV-p@WHAMP-2.0

And rebuilt all packages locally.

Then reran

EpiModel-p/inst/make_data.R
EpiModel-p/model-run.R

And I am still getting this error at the point of simulation:

```
> sim <- netsim(ee.netest.full, param, init, control)

Starting Network Simulation...
 Error in eval(predvars, data, env) : object 'geogYN' not found 
```

Note:  The `make_data.R` script does use geography to pull the WA state respondents from ARTnet in the `build_epistats` steop.  That's not the workflow we want (ultimately), but I've been trying to stay as close to @syzoekao's workflow as possible to debug another issue.  When I use this workflow with the original `EpiModel-p@WHAMP` branch, I don't get this error.  I do get another error that looks like the edges go to zero in the `inst` network -- that's the error I'm hoping to debug ... but in the new 2.0 branch.

Just a note -- @syzoekao i think we should move the model-run.R into the inst folder.  I already have my versions of make_data and model-run there.  And it would be good to use '_' or '-' consistently.  Let's stick with '_'

**Comment by andsv2** [comment]
Afternoon @martinamorris: for EpiModelHIV, can you humor me and instead of "clean and rebuilding" from a downloaded repo, use 
```
remove.packages("EpiModelHIV")
remotes::install_github("EpiModel/EpiModelHIV-p", ref = "WHAMP-2.0")
```

**Comment by martinamorris** [comment]
@andsv2 did that; no change

**Comment by andsv2** [comment]
Hey @martinamorris, is it possible to get a look at your epistats and netstats objects as well as an initialized dat? Things are working here on my end (even using DSData) so I'm a bit at a loss.

**Comment by martinamorris** [comment]
It's working!  I think I had forgotten to run make_data.

So, now on to the actual debugging.  During simulation, I'm getting this:

```
Epidemic Simulation
----------------------------
Simulation: 1/1
Timestep: 5/260
Prevalence: 899
Population Size: 14429
----------------------------Error in rep(1, nrow(el.oo)) : invalid 'times' argument
```
I'm guessing this means we have 0 edges in the `oo` network.  But that's where I'm headed next.  @andsv2 are you able to replicate this behavior?

**Comment by andsv2** [comment]
@martinamorris: if `el.oo` has no rows, you should still get an object from `rep(1, nrow(el.oo))`. That error would seem to indicate that `el.oo` is not a matrix or data.frame -> something is going on with the edgelist construction. Can you step in to the function and see - at the creation of `el` (line 48) - what kind of structure you have?

**Comment by martinamorris** [comment]
i did have one sim go thru to completion, so it seems like a stochastic 
error.

stepping in, i can see that the starting edges values in each network are 
way off.  they are right on in the fit$newnetworks, so there's a problem 
in the initialization.

in ARTnet, that's handled by netparams and netstats -- both of which are 
radically different for the ergm.ego workflow.

Zoe used the ARTnet functions -- and was able to get a model with no 
cross-net concurrency to work, but the model i'm working with, which has a 
cross-net conc term, generates these errors. (note we debugged up to this 
point, the netdx are spot on for both models).

in truth, i'm amazed Zoe got anything to work, given the disconnect 
between the ergm.ego fit object and the way build_netstats works.  among 
other things, ergm.ego is using weights to resample to the desired pop 
size.

in any case, i need to revise that bit of the workflow so that netstats 
are taken directly from the ergm.ego fit$newnetwork object, and see if 
that fixes things.

**Comment by martinamorris** [comment]
Debugging showed that yes, the error `Error in rep(1, nrow(el.oo)) : invalid 'times' argument` was caused by the edges in the inst network stochastically fluctuating to 0.  

This is because in the `ergm.ego` workflow, the target stats are derived from the alter list (from the partner modules).  That works pretty well for the main and persistent partners, as very few respondents report additional partners beyond those in the modules.  But it doesn't work for the inst partners -- in this case the additional partners are the majority.  We capture roughly a week's worth of inst partners in the modules (coincidentally), so when this number is divided by 52 (in the `netest` conversion) we severely underestimate the inst partner count.

In the ARTnet target stats workflow, the inst network is parameterized using the summary variable `count.oo.part`, so all the inst partners are accounted for.

The solution (for now) is to use the target stats workflow for the inst network, and the `ergm.ego` workflow for the main/casl networks.
