### ISSUE TITLE
Checking target stats constructions

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/ARTnet#29]
I'm going to be using the target stats approach for the inst network (see #25), so I'm modifying the `NetParams.R` and `NetStats.R` scripts (just pulling the components needed for TS construction).

The basic approach follows yours:  

1. model the per-capital predictions for each term (NetParams)
2. calculate factor level distributions in the observed data  (NetStats)
3. calculate the TS:  (NetStats)  
  * edges:  TS = per-capita prediction * network size / 2
  * nf terms:  TS = per-capita prediction * factor level distn * network size
  * nm terms: TS = per-capita prediction * nf term  / 2
  * continuous covariates:  TS = per-capita prediction * edges

There should be consistency in some of these TS values (i.e., sum(nf) = edges).  And I'm getting that for everything except the nf.risk.grp:

```
> out$edges
[1] 693.3053
> sum(out$nodefactor_race)
[1] 1386.642
> sum(out$nodefactor_race)/2
[1] 693.3208
> sum(out$nodefactor_region)
[1] 1386.558
> sum(out$nodefactor_age.grp)
[1] 1386.499
> sum(out$nodefactor_deg.mainb)
[1] 1386.555
> sum(out$nodefactor_deg.caslb)
[1] 1385.487
> sum(out$nodefactor_diag.status)
[1] 1386.655
> sum(out$nodefactor_risk.grp)
[1] 1419.08
``` 

Also, there should be consistency between the two specifications for nm:  sum(nm(diff=T)) = sum(nm(diff=F)).  I'm getting something close but not exact:

```
> sum(out$nodematch_race)
[1] 460.1333
> sum(out$nodematch_race_unif)
[1] 456.3974
```

So, my questions are:

1. Did you check all of these for your ARTnet workflow?  
2. Did you find/fix any discrepancies?

**Comment by andsv2** [comment]
@martinamorris good morning, I will review this workflow to see why you're not getting internal consistency. However, it was my understanding that all nodefactor estimates should be divided by two to get consistency with overall edges. 

As for differences observed (particularly with respect to attributes that are assigned randomly) there is definitely the potential for sizeable differences between edges and attribute level counts.

Either way I will take a look at both of these.

**Comment by martinamorris** [comment]
thx @andsv2, and yes, the nf estimates should be divided by 2 -- i noted that in the description, and demonstrated in the output.  the issue is not the values of 1386, those are all correct (693x2).  the issue is with nf.risk.grp, where the value is 1419.

the issue here is not consistency of the scaled up TS with the original dataset -- given the scaleup in network size, there will always be differences.  the issue is the *internal consistency* of the scaled up TS.

so -- i'm just curious whether your scaled-up TS, at the end, are internally consistent.

note:  i don't use random assignment, even in my target stats workflow.  i calculate the factor distributions from the `egodata$egos` -- the wide dataset.   this is all you need to construct the TS.  the reason Sam sets up the out$attr vectors with assigned attributes is because he will assign these attributes to the nodeset in his initial network.

when i get to the stage of constructing my initial network, i do this with `ergm.ego` -- it scales up the nodeset appropriately (roughly, by weighted resampling), and the nodes come with all of their attributes intact, so i never have to assign attributes to nodes.

**Comment by andsv2** [comment]
@martinamorris whoops. . .sorry for that assumption. That's egg on my face there.

And yes, we went over the target stats results and accounted for any internal differences between the target statistics. 
[ARTnet_Development.docx](https://github.com/EpiModel/ARTnet/files/4314038/ARTnet_Development.docx)

**Comment by martinamorris** [comment]
Thx for the document -- the focus there is comparisons between methods, rather than consistency within method.  And you didn't yet include the nf.risk.grp variable, which is the one I'm finding inconsistent.

The diffs I'm seeing are not that large, so I'm not really concerned.  If I want to make them consistent, that's easy enough to do.  But I'd be curious to see if your approach produces internally consistent TS at the end.
