### ISSUE TITLE
Example netest() call you use?

### ISSUE THREAD

**Issue by martinamorris** [EpiModel/ARTnet#30]
The ARTnet workflow stops just at this point.  There needs to be some careful selection of the target stats to avoid overparameterization in the call to ergm.

Can you point me to any examples of your scripts for prepping the data inputs for `netest()`?

**Comment by andsv2** [comment]
Hey @martinamorris; if I use: 

```
epistats <- build_epistats(geog.lvl = "state", geog.cat = "WA", race = TRUE)
netparams <- build_netparams(epistats)
netstats <- build_netstats
``` 
I get overall edges and implied edges from risk group of 469. For general testing I used the ARTnetIntro document in the vignettes for ARTnet. 

If this isn't what you're looking for please let me know.
