### ISSUE TITLE
Is the questionnaire available?

### ISSUE THREAD

**Issue by tillahoffmann** [EpiModel/ARTnet#54]
Thanks for the great summary of results in https://doi.org/10.1016/j.epidem.2020.100386! Is the questionnaire provided to participants publicly available?

**Comment by smjenness** [comment]
Hi @tillahoffmann : are you looking for the survey instrument or the dataset? Happy to send either but the procedures are different. Please follow up with my by email with more details: samuel.m.jenness@emory.edu
